# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - AnyCPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: IxoxoNHibernate.sln     # path to Visual Studio solution or project
  publish_wap: false               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true              # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: normal